const SOURCE={owner:'GladistoneSouza',repo:'Projeto_Genesis',branch:'main',root:'Projeto Genesis/Projeto Genesis/'};
const API=`https://api.github.com/repos/${SOURCE.owner}/${SOURCE.repo}`;
const RAW=`https://raw.githubusercontent.com/${SOURCE.owner}/${SOURCE.repo}`;
const HIDE=new Set(['genesis-capitulo-01.md']);
const state={sha:'',treeSha:'',docs:[],tree:[],current:null,cache:new Map(),indexed:false,view:'home',busy:false};
const $=s=>document.querySelector(s);const el={menu:$('#menu'),brand:$('#brand'),search:$('#search'),refresh:$('#refresh'),theme:$('#theme'),commit:$('#commit'),sidebar:$('#sidebar'),homeLink:$('#home-link'),tree:$('#tree'),status:$('#status'),home:$('#home'),results:$('#results'),doc:$('#doc'),reader:$('#reader'),title:$('#doc-title'),path:$('#doc-path'),meta:$('#doc-meta'),badges:$('#badges'),outline:$('#outline'),prev:$('#prev'),next:$('#next'),toast:$('#toast')};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const norm=s=>{const a=[];for(const p of String(s||'').replaceAll('\\','/').split('/')){if(!p||p==='.')continue;p==='..'?a.pop():a.push(p)}return a.join('/')};
const dir=s=>{const a=s.split('/');a.pop();return a.join('/')};const stem=s=>s.split('/').pop().replace(/\.md$/i,'');const short=()=>state.sha?state.sha.slice(0,7):'…';const enc=s=>s.split('/').map(encodeURIComponent).join('/');
const rawUrl=p=>`${RAW}/${state.sha}/${enc(SOURCE.root+norm(p))}`;const cat=p=>/^genesis-\d{2}\//.test(p)?'Capítulo':p.startsWith('docs/lexicos/')?'Léxico':p.startsWith('docs/metodo/')?'Método':p==='docs/posicoes.md'?'Posições':p==='docs/fios-canonicos.md'?'Fios canônicos':p.startsWith('docs/')?'Governança':p==='prefacio.md'?'Livro':p==='genesis.md'?'Introdução':'Documento';const glyph=p=>({'Capítulo':'א','Léxico':'אב','Método':'N','Posições':'◆','Fios canônicos':'⌁','Governança':'§','Livro':'✦','Introdução':'ב'})[cat(p)]||'·';
function toast(s){el.toast.textContent=s;el.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.add('hidden'),2200)}
async function gj(path){const r=await fetch(API+path,{cache:'no-store',headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}});if(!r.ok)throw new Error(r.status===403?'Limite temporário da API do GitHub.':`GitHub respondeu ${r.status}.`);return r.json()}
async function head(){const b=await gj(`/branches/${encodeURIComponent(SOURCE.branch)}`);return{sha:b.commit.sha,tree:b.commit.commit.tree.sha}}
function titlePath(p){if(p==='prefacio.md')return'Prefácio';if(p==='genesis.md')return'Gênesis — Introdução';return stem(p).replace(/^\d{2}-/,'').replaceAll('-',' ').replace(/(^|\s)\S/g,m=>m.toLocaleUpperCase('pt-BR'))}
function titleRaw(raw,fallback){const m=raw.match(/^#\s+(.+)$/m);return m?m[1].replace(/[\*_`]/g,'').trim():fallback}
function nested(docs){const root={f:new Map(),d:[]};for(const d of docs){const a=d.path.split('/');a.pop();let c=root;for(const x of a){if(!c.f.has(x))c.f.set(x,{f:new Map(),d:[]});c=c.f.get(x)}c.d.push(d)}const walk=n=>[...[...n.f].sort(([a],[b])=>a.localeCompare(b,'pt-BR',{numeric:true})).map(([name,v])=>({type:'folder',name,children:walk(v)})),...n.d.sort((a,b)=>a.path.localeCompare(b.path,'pt-BR',{numeric:true})).map(d=>({type:'doc',...d}))];return walk(root)}
function pretty(s){if(s==='docs')return'Documentação';if(s==='lexicos')return'Léxicos';if(s==='metodo')return'Método';if(/^genesis-\d{2}$/.test(s))return`Gênesis ${Number(s.slice(-2))}`;return s.replaceAll('-',' ')}
function treeHtml(nodes,depth=0){return nodes.map(n=>n.type==='folder'?`<details ${depth<1||n.name==='genesis-01'?'open':''}><summary>› ${esc(pretty(n.name))}</summary><div>${treeHtml(n.children,depth+1)}</div></details>`:`<button data-doc="${esc(n.path)}">${esc(n.title)}</button>`).join('')}
function renderTree(){el.tree.innerHTML=treeHtml(state.tree);el.tree.querySelectorAll('[data-doc]').forEach(b=>b.onclick=()=>{openDoc(b.dataset.doc);el.sidebar.classList.remove('open')});markActive()}
function markActive(){el.tree.querySelectorAll('[data-doc]').forEach(b=>b.classList.toggle('active',state.view==='doc'&&b.dataset.doc===state.current));el.homeLink.classList.toggle('active',state.view==='home')}
async function loadSource(announce=false){if(state.busy)return;state.busy=true;el.refresh.classList.add('spin');try{const old=state.sha,h=await head();if(old&&h.sha===old){if(announce)toast(`Já está no main mais recente · ${short()}`);return}const t=await gj(`/git/trees/${h.tree}?recursive=1`);const docs=t.tree.filter(x=>x.type==='blob'&&x.path.startsWith(SOURCE.root)).map(x=>({...x,path:x.path.slice(SOURCE.root.length)})).filter(x=>x.path.toLowerCase().endsWith('.md')&&!HIDE.has(x.path)&&!x.path.split('/').some(y=>y.startsWith('.'))).map(x=>({path:x.path,title:titlePath(x.path),sha:x.sha,size:x.size||0}));state.sha=h.sha;state.treeSha=h.tree;state.docs=docs;state.tree=nested(docs);state.cache.clear();state.indexed=false;renderTree();renderHome();el.status.classList.add('ok');el.commit.textContent=`main · ${short()}`;el.meta.textContent=`Fonte viva · main ${short()}`;if(old&&announce)toast(`main atualizado · ${old.slice(0,7)} → ${short()}`);if(state.current&&docs.some(d=>d.path===state.current))await openDoc(state.current,'',true)}finally{state.busy=false;el.refresh.classList.remove('spin')}}
async function raw(p){const k=`${state.sha}:${p}`;if(state.cache.has(k))return state.cache.get(k);const r=await fetch(rawUrl(p));if(!r.ok)throw new Error(`Não consegui ler ${p}.`);const s=await r.text();state.cache.set(k,s);return s}
function byPath(p){return state.docs.find(d=>d.path===p)}function resolve(target){const clean=target.split('#')[0].trim(),anchor=target.includes('#')?target.slice(target.indexOf('#')+1):'',w=clean.toLowerCase().endsWith('.md')?clean:`${clean}.md`,rel=norm(`${dir(state.current||'')}/${w}`);let d=byPath(rel)||byPath(norm(w));if(!d){const a=state.docs.filter(x=>stem(x.path)===stem(w));d=a.length===1?a[0]:a.find(x=>dir(x.path)===dir(state.current||''))||a[0]}return d?{path:d.path,anchor}:null}
function wiki(s){return s.replace(/\[\[([^\]|]+?)(?:\|([^\]]+))?\]\]/g,(_,t,l)=>{const r=resolve(t),text=(l||t).trim();return r?`[${text}](wiki:${encodeURIComponent(r.path)}${r.anchor?`#${r.anchor}`:''})`:`${text} ⚠`})}
let mermaid=null;try{const m=await import('https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs');mermaid=m.default;mermaid.initialize({startOnLoad:false,securityLevel:'strict',theme:'neutral'})}catch(e){console.warn(e)}
const md=window.markdownit?window.markdownit({html:false,linkify:true,typographer:true}).use(window.markdownitFootnote||(()=>{})):{render:s=>`<pre>${esc(s)}</pre>`,renderer:{rules:{}},utils:{escapeHtml:esc}};if(window.markdownit){const f=md.renderer.rules.fence?.bind(md.renderer.rules);md.renderer.rules.fence=(tokens,i,o,e,self)=>{const t=tokens[i];if((t.info||'').trim().toLowerCase()==='mermaid'){const c=md.utils.escapeHtml(t.content);return`<div class="diagram"><div class="mermaid">${c}</div></div>`}return f?f(tokens,i,o,e,self):self.renderToken(tokens,i,o)}}
function links(container){container.querySelectorAll('a[href]').forEach(a=>{const h=a.getAttribute('href');if(!h)return;if(h.startsWith('wiki:')){a.dataset.doc=decodeURIComponent(h.slice(5).split('#')[0]);a.dataset.anchor=h.includes('#')?h.slice(h.indexOf('#')+1):'';a.href='#'}else if(/^https?:|^mailto:|^tel:/i.test(h)){a.target='_blank';a.rel='noopener noreferrer'}else if(!h.startsWith('#')&&h.split('#')[0].toLowerCase().endsWith('.md')){const r=resolve(h);if(r){a.dataset.doc=r.path;a.dataset.anchor=r.anchor;a.href='#'}}});container.querySelectorAll('img[src]').forEach(i=>{const s=i.getAttribute('src');if(!s||/^https?:|^data:/i.test(s))return;i.src=rawUrl(norm(`${dir(state.current)}/${decodeURIComponent(s)}`));i.loading='lazy'});container.onclick=e=>{const a=e.target.closest('a[data-doc]');if(!a)return;e.preventDefault();openDoc(a.dataset.doc,a.dataset.anchor||'')}}
function badges(s){const set=new Set();for(const re of [/\bN[1-5]\b/g,/\bF[1-3]\b/g,/\bC[1-5]\b/g,/\bP[1-3]\b/g,/\bIA(?:✓|:[A-Za-z+]+)/g])for(const m of s.matchAll(re))set.add(m[0]);el.badges.innerHTML=set.size?[...set].sort().map(x=>`<span>${esc(x)}</span>`).join(''):'<em>—</em>'}
function outline(){const used=new Set(),a=[];el.doc.querySelectorAll('h2,h3,h4').forEach(h=>{let id=h.textContent.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'secao',b=id,n=2;while(used.has(id))id=`${b}-${n++}`;used.add(id);h.id=id;a.push(`<a class="l${h.tagName.slice(1)}" href="#${id}">${esc(h.textContent)}</a>`)});el.outline.innerHTML=a.join('')||'<em>—</em>'}
function rtl(){const re=/[\u0590-\u05ff]/g;el.doc.querySelectorAll('p,li,td,th,blockquote').forEach(x=>{const t=x.textContent||'',n=t.match(re)?.length||0,l=t.replace(/\s/g,'').length||1;if(n>=4&&n/l>.35){x.dir='rtl';x.lang='he'}})}
function neighbors(p){const same=state.docs.filter(d=>dir(d.path)===dir(p)),list=same.length>1?same:state.docs,i=list.findIndex(d=>d.path===p);return{prev:i>0?list[i-1]:null,next:i>=0&&i<list.length-1?list[i+1]:null}}
function nav(p){const n=neighbors(p);el.prev.disabled=!n.prev;el.next.disabled=!n.next;el.prev.dataset.doc=n.prev?.path||'';el.next.dataset.doc=n.next?.path||''}
async function openDoc(p,anchor='',keep=false){try{state.view='doc';const scroll=el.reader.scrollTop,s=await raw(p),d=byPath(p),title=titleRaw(s,d?.title||titlePath(p));if(d)d.title=title;state.current=p;el.doc.innerHTML=md.render(wiki(s));el.doc.insertAdjacentHTML('afterbegin',`<div class="doc-top"><span>${glyph(p)}</span><div><b>${esc(cat(p))}</b><small>${esc(p)}</small></div><span>main ${short()}</span></div>`);links(el.doc);badges(s);outline();rtl();if(mermaid&&el.doc.querySelector('.mermaid'))try{await mermaid.run({nodes:[...el.doc.querySelectorAll('.mermaid')]})}catch(e){console.warn(e)}el.title.textContent=title;el.path.textContent=p;el.meta.textContent=`main ${short()} · lido agora do GitHub`;document.title=`${title} · Projeto Gênesis`;nav(p);markActive();el.home.classList.add('hidden');el.results.classList.add('hidden');el.doc.classList.remove('hidden');history.replaceState(null,'',`${location.pathname}#doc=${encodeURIComponent(p)}`);if(keep)el.reader.scrollTop=scroll;else if(anchor)requestAnimationFrame(()=>document.getElementById(anchor)?.scrollIntoView({behavior:'smooth'}));else el.reader.scrollTo({top:0})}catch(e){el.home.classList.add('hidden');el.doc.classList.remove('hidden');el.doc.innerHTML=`<h1>Não consegui abrir</h1><p>${esc(e.message)}</p>`}}
function card(k,t,x,p){return`<button class="card" data-doc="${esc(p)}"><small>${esc(k)}</small><strong>${esc(t)}</strong><p>${esc(x)}</p><b>Abrir →</b></button>`}
function renderHome(){const ch=state.docs.filter(d=>d.path.startsWith('genesis-01/')).length,lx=state.docs.filter(d=>d.path.startsWith('docs/lexicos/')).length,mt=state.docs.filter(d=>d.path.startsWith('docs/metodo/')).length;el.home.innerHTML=`<section class="hero"><div><span class="overline">Biblioteca de estudo bíblico</span><h1>Gênesis, com o texto aberto<br><em>e as perguntas à vista.</em></h1><p>O leitor consulta o <strong>main atual</strong> do Projeto Gênesis. Mudou um Markdown? Atualize e leia a versão nova — sem servidor próprio e sem redeploy do conteúdo.</p><div class="hero-actions"><button class="primary" data-doc="genesis-01/00-como-usar.md">Começar Gênesis 1 →</button><button data-doc="prefacio.md">Ler o prefácio</button></div><div class="live"><i></i><b>main ${short()}</b><span>fonte viva no GitHub</span></div></div><aside class="seal"><b>בְּרֵאשִׁית</b><span></span><small>no princípio</small></aside></section><section class="section"><div class="section-head"><div><span class="overline">Portas de entrada</span><h2>Escolha como quer estudar</h2></div><small>${state.docs.length} documentos no main</small></div><div class="cards">${card('Capítulo 1','Leitura guiada',`${ch} documentos entre preparação e estudo.`,'genesis-01/00-como-usar.md')}${card('Hebraico','Texto original','Texto, transliteração e termos decisivos.','genesis-01/01-texto-hebraico.md')}${card('Wiki lexical','Palavras em disputa',`${lx} notas de corpus e léxicos.`,'docs/lexicos/00-indice.md')}${card('Método','Como o projeto sabe',`${mt} notas sobre nível, fonte e camada.`,'docs/metodo/00-indice.md')}${card('Registro','Posições e faturas','O que foi adotado, aberto e o preço de cada posição.','docs/posicoes.md')}${card('Cânon','Fios canônicos','Temas plantados em Gênesis e pagos pelo restante do cânon.','docs/fios-canonicos.md')}</div></section><section class="method"><div><span class="overline">Régua do projeto</span><h2>Nem toda afirmação pesa igual.</h2><p>Os marcadores do próprio Markdown aparecem durante a leitura.</p></div><div class="axes"><div><b>N</b><span>N1–N5</span><small>texto</small></div><div><b>F</b><span>F1–F3</span><small>fonte</small></div><div><b>C</b><span>C1–C5</span><small>camada</small></div><div><b>P</b><span>P1–P3</span><small>pergunta</small></div></div></section>`;el.home.querySelectorAll('[data-doc]').forEach(b=>b.onclick=()=>openDoc(b.dataset.doc))}
function showHome(){state.view='home';state.current=null;el.results.classList.add('hidden');el.doc.classList.add('hidden');el.home.classList.remove('hidden');el.title.textContent='Visão geral';el.path.textContent='Projeto Gênesis';el.meta.textContent=`Fonte viva · main ${short()}`;el.badges.innerHTML='<em>—</em>';el.outline.innerHTML='<em>—</em>';el.prev.disabled=el.next.disabled=true;history.replaceState(null,'',location.pathname);markActive();el.reader.scrollTo({top:0})}
function strip(s){return s.replace(/```[\s\S]*?```/g,' ').replace(/!\[[^\]]*\]\([^)]*\)/g,' ').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g,(_,a,b)=>b||a).replace(/[#>*_`~|[\]()-]/g,' ').replace(/\s+/g,' ').trim()}
async function index(){if(state.indexed)return;toast('Preparando busca no main…');const q=[...state.docs],workers=Array.from({length:Math.min(6,q.length)},async()=>{while(q.length){const d=q.shift();try{const s=await raw(d.path);d.title=titleRaw(s,d.title)}catch{}}});await Promise.all(workers);state.indexed=true;renderTree()}
async function search(q){q=q.trim();if(q.length<2){el.results.classList.add('hidden');state.view==='home'?el.home.classList.remove('hidden'):el.doc.classList.remove('hidden');return}await index();const n=q.toLocaleLowerCase('pt-BR'),r=[];for(const d of state.docs){const s=state.cache.get(`${state.sha}:${d.path}`)||'',th=d.title.toLocaleLowerCase('pt-BR').includes(n),ph=d.path.toLocaleLowerCase('pt-BR').includes(n),bh=s.toLocaleLowerCase('pt-BR').includes(n);if(th||ph||bh){const clean=strip(s),i=clean.toLocaleLowerCase('pt-BR').indexOf(n),sn=i<0?clean.slice(0,160):`${i>60?'…':''}${clean.slice(Math.max(0,i-60),i+n.length+100)}…`;r.push({d,sn,score:(th?10:0)+(ph?4:0)+(bh?1:0)})}}r.sort((a,b)=>b.score-a.score);el.home.classList.add('hidden');el.doc.classList.add('hidden');el.results.classList.remove('hidden');el.results.innerHTML=`<header><span class="overline">Busca · main ${short()}</span><h1>${r.length} resultado${r.length===1?'':'s'}</h1></header>${r.slice(0,50).map(x=>`<button class="result" data-doc="${esc(x.d.path)}"><span>${glyph(x.d.path)}</span><div><small>${esc(cat(x.d.path))}</small><strong>${esc(x.d.title)}</strong><code>${esc(x.d.path)}</code><p>${esc(x.sn)}</p></div><span>→</span></button>`).join('')||'<p>Nada encontrado.</p>'}`;el.results.querySelectorAll('[data-doc]').forEach(b=>b.onclick=()=>openDoc(b.dataset.doc));el.reader.scrollTo({top:0})}
function theme(){const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem('genesis-theme',n)}
function bind(){el.brand.onclick=showHome;el.homeLink.onclick=showHome;el.menu.onclick=()=>el.sidebar.classList.toggle('open');el.refresh.onclick=()=>loadSource(true);el.theme.onclick=theme;el.prev.onclick=()=>el.prev.dataset.doc&&openDoc(el.prev.dataset.doc);el.next.onclick=()=>el.next.dataset.doc&&openDoc(el.next.dataset.doc);let t;el.search.oninput=()=>{clearTimeout(t);t=setTimeout(()=>search(el.search.value),230)};addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();el.search.focus()}if(e.key==='Escape')el.sidebar.classList.remove('open')})}
async function boot(){const saved=localStorage.getItem('genesis-theme');if(saved)document.documentElement.dataset.theme=saved;else if(matchMedia('(prefers-color-scheme:dark)').matches)document.documentElement.dataset.theme='dark';bind();try{await loadSource();const p=new URLSearchParams(location.hash.replace(/^#/,'')),d=p.get('doc');d&&byPath(d)?await openDoc(d):showHome()}catch(e){el.doc.classList.remove('hidden');el.home.classList.add('hidden');el.doc.innerHTML=`<h1>Não consegui carregar o projeto</h1><p>${esc(e.message)}</p>`}if('serviceWorker'in navigator)try{await navigator.serviceWorker.register('./sw.js')}catch(e){console.warn(e)}}boot();
